### ISSUE TITLE
Looking for more features.

### ISSUE THREAD

**Issue by Insticthere** [tbdsux/kuryana#28]
I was wondering if another endpoint for the api for the site's List pages, https://mydramalist.com/list/ (eg. https://mydramalist.com/list/1xrQlbW3) These can also be private and for people instead of drama's.

I think it would be a nice addition to the api, moreover me along with many people might have a use for it. Let me know if its possible from your side!

**Comment by Insticthere** [comment]
Hey, thanks for replying and making a push
I found out two slight issue tho, 
https://kuryana-git-implement-lists-api-theboringdude.vercel.app/list/1xrQlbW3 gives, 
```json
{
  "error": true,
  "code": 400,
  "description": "An unexpected error occurred."
}
```
This is because it is a private list This can be fixed easily as we can check for `<h1 class="text-lg title m-b">This list is private.</h1>` under `box-body`. eg https://mydramalist.com/list/1xrQlbW3

Another, the app ends up crashing when we are using a user list instead of a drama list. The best way i found out to differentiate them is via comparing them via the div `<div class="list-bars p-y-sm m-b text-black-lt"> ` the showlist has a `<i class="far fa-tv m-r-xs"></i>` While the actors has a `<i class="far fa-user m-r-xs"></i>` inside the div.

along with this i was wondering for the future for this repo 🤔 thanks for making this btw!

**Comment by tbdsux** [comment]
```js
{
  "code": 400,
  "error": true,
  "description": {
    "title": "This list is private.",
    "info": "You can see this page because the URL you are accessing cannot be found."
  }
}
```

This is currently the best we can have with error messages.

**Comment by Insticthere** [comment]
> I'm sorry, I need more examples for this ...

My bad i got my examples messed up, https://mydramalist.com/list/4YWA8y9L this leads to the vercel error page when used on https://kuryana-git-implement-lists-api-theboringdude.vercel.app/list/4YWA8y9L

> I'm thinking of rather making this a library or moving main scraping functions to a library and make this api extend from it.

Sounds great but please make sure there is a way to use this as a serverless api as i dont use it on python

That is a good error message i dont see a problem, just i dont get that error message right now eg. https://kuryana-git-implement-lists-api-theboringdude.vercel.app/list/1xrQlbW3

Not sure if its intended but https://kuryana-git-implement-lists-api-theboringdude.vercel.app/list/1312313123 gives 404 which can be used but not sure about the above one

**Comment by tbdsux** [comment]
> My bad i got my examples messed up, https://mydramalist.com/list/4YWA8y9L this leads to the vercel error page when used on https://kuryana-git-implement-lists-api-theboringdude.vercel.app/list/4YWA8y9L

Will try to work on it later..

`https://kuryana-git-implement-lists-api-theboringdude.vercel.app/list/1xrQlbW3` this is a preview url, please use the main api url which is:
```
https://kuryana.vercel.app
```

> Sounds great but please make sure there is a way to use this as a serverless api as i dont use it on python

Of course, but there is still no plan about it.

**Comment by tbdsux** [comment]
> My bad i got my examples messed up, https://mydramalist.com/list/4YWA8y9L this leads to the vercel error page when used on https://kuryana-git-implement-lists-api-theboringdude.vercel.app/list/4YWA8y9L

I have added a commit feature for this one. 
Examples:
```
https://kuryana.vercel.app/list/1xrQrzD3
https://kuryana.vercel.app/list/4YWA8y9L
```

**Comment by Insticthere** [comment]
Thanks for this, really appreciate it
